name: Daily update
on:
  schedule:
  - cron: '0 16 * * *'
  push:
    branches:
      - 'master'
jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:[BUPT,BNU]
    env:
      TZ: Asia/Shanghai
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
      - name: Update ${{matrix.directory}} release
        run: |
          DIR="${{matrix.directory}}"
          make -C $DIR
          RELEASE_ID=$(gh release view $DIR --json databaseId -q .databaseId || echo "")
          if [[ -z "${RELEASE_ID}" ]]; then
            gh release create $DIR --title "$DIR" --prerelease
            RELEASE_ID=$(gh release view $DIR --json databaseId -q .databaseId)
          fi
          gh release upload $DIR $DIR/*.png --clobber
